/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Apr 06 14:36:58 MSK 2017
 */
package ru.breffi.entityTypeConverterImpl.companyConverter.sfdto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist BF_Emloyee_County__c
 */
public enum BF_Company__c_BF_Emloyee_CountyEnum {

    // Адмиралтейский
    АДМИРАЛТЕЙСКИЙ("Адмиралтейский"),
    // ВАО
    ВАО("ВАО"),
    // Василеостровский
    ВАСИЛЕОСТРОВСКИЙ("Василеостровский"),
    // Выборгский
    ВЫБОРГСКИЙ("Выборгский"),
    // ЗАО
    ЗАО("ЗАО"),
    // Зеленоград
    ЗЕЛЕНОГРАД("Зеленоград"),
    // Калининский
    КАЛИНИНСКИЙ("Калининский"),
    // Кировский
    КИРОВСКИЙ("Кировский"),
    // Колпинский
    КОЛПИНСКИЙ("Колпинский"),
    // Красногвардейский
    КРАСНОГВАРДЕЙСКИЙ("Красногвардейский"),
    // Красносельский
    КРАСНОСЕЛЬСКИЙ("Красносельский"),
    // Кронштадтский
    КРОНШТАДТСКИЙ("Кронштадтский"),
    // Курортный
    КУРОРТНЫЙ("Курортный"),
    // Московский
    МОСКОВСКИЙ("Московский"),
    // Невский
    НЕВСКИЙ("Невский"),
    // Петроградский
    ПЕТРОГРАДСКИЙ("Петроградский"),
    // Петродворцовый
    ПЕТРОДВОРЦОВЫЙ("Петродворцовый"),
    // Приморский
    ПРИМОРСКИЙ("Приморский"),
    // Пушкинский
    ПУШКИНСКИЙ("Пушкинский"),
    // САО
    САО("САО"),
    // СВАО
    СВАО("СВАО"),
    // СЗАО
    СЗАО("СЗАО"),
    // Фрунзенский
    ФРУНЗЕНСКИЙ("Фрунзенский"),
    // ЦАО
    ЦАО("ЦАО"),
    // Центральный
    ЦЕНТРАЛЬНЫЙ("Центральный"),
    // ЮАО
    ЮАО("ЮАО"),
    // ЮВАО
    ЮВАО("ЮВАО"),
    // ЮЗАО
    ЮЗАО("ЮЗАО");

    final String value;

    private BF_Company__c_BF_Emloyee_CountyEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static BF_Company__c_BF_Emloyee_CountyEnum fromValue(String value) {
        for (BF_Company__c_BF_Emloyee_CountyEnum e : BF_Company__c_BF_Emloyee_CountyEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
