/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Apr 06 14:36:58 MSK 2017
 */
package ru.breffi.entityTypeConverterImpl.companyConverter.sfdto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist BF_Company_type__c
 */
public enum BF_Company__c_BF_Company_typeEnum {

    // ¿ÔÚÂÍ‡
    ¿œ“≈ ¿("¿ÔÚÂÍ‡"),
    // Àœ”
    Àœ”("Àœ”");

    final String value;

    private BF_Company__c_BF_Company_typeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static BF_Company__c_BF_Company_typeEnum fromValue(String value) {
        for (BF_Company__c_BF_Company_typeEnum e : BF_Company__c_BF_Company_typeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
