/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Apr 06 14:36:58 MSK 2017
 */
package ru.breffi.entityTypeConverterImpl.employee.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.google.gson.annotations.SerializedName;

/**
 * Salesforce Enumeration DTO for picklist BF_Emloyee_speciality__c
 */
public enum Employee__c_BF_Emloyee_specialityEnum {

    // Венеролог
	@SerializedName("Венеролог")ВЕНЕРОЛОГ("Венеролог"),
    // Врач общей практики
	@SerializedName("Врач общей практики")ВРАЧ_ОБЩЕЙ_ПРАКТИКИ("Врач общей практики"),
    // Гастроэнтеролог
	@SerializedName("Гастроэнтеролог")ГАСТРОЭНТЕРОЛОГ("Гастроэнтеролог"),
    // Гинеколог
	@SerializedName("Гинеколог")ГИНЕКОЛОГ("Гинеколог"),
    // Дерматолог
	@SerializedName("Дерматолог")ДЕРМАТОЛОГ("Дерматолог"),
    // Инфекционист
	@SerializedName("Инфекционист")ИНФЕКЦИОНИСТ("Инфекционист"),
    // Отоларинголог
	@SerializedName("Отоларинголог")ОТОЛАРИНГОЛОГ("Отоларинголог"),
    // Педиатр
	@SerializedName("Педиатр")ПЕДИАТР("Педиатр"),
    // Пульмонолог
	@SerializedName("Пульмонолог")ПУЛЬМОНОЛОГ("Пульмонолог"),
    // Терапевт
	@SerializedName("Терапевт")ТЕРАПЕВТ("Терапевт"),
    // Уролог
	@SerializedName("Уролог")УРОЛОГ("Уролог");

    final String value;

    private Employee__c_BF_Emloyee_specialityEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Employee__c_BF_Emloyee_specialityEnum fromValue(String value) {
        for (Employee__c_BF_Emloyee_specialityEnum e : Employee__c_BF_Emloyee_specialityEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
