/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Apr 06 14:36:58 MSK 2017
 */
package ru.breffi.entityTypeConverterImpl.employee.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist BF_Emloyee_category__c
 */
public enum Employee__c_BF_Emloyee_categoryEnum {

    // A
    A("A"),
    // B
    B("B"),
    // C
    C("C");

    final String value;

    private Employee__c_BF_Emloyee_categoryEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Employee__c_BF_Emloyee_categoryEnum fromValue(String value) {
        for (Employee__c_BF_Emloyee_categoryEnum e : Employee__c_BF_Emloyee_categoryEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
