/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Apr 06 14:36:58 MSK 2017
 */
package ru.breffi.entityTypeConverterImpl.employee.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject Employee__c
 */
@XStreamAlias("Employee__c")
public class Employee__c extends AbstractSObjectBase {

    // ConnectionReceivedId
    private String ConnectionReceivedId;

    @JsonProperty("ConnectionReceivedId")
    public String getConnectionReceivedId() {
        return this.ConnectionReceivedId;
    }

    @JsonProperty("ConnectionReceivedId")
    public void setConnectionReceivedId(String ConnectionReceivedId) {
        this.ConnectionReceivedId = ConnectionReceivedId;
    }

    // ConnectionSentId
    private String ConnectionSentId;

    @JsonProperty("ConnectionSentId")
    public String getConnectionSentId() {
        return this.ConnectionSentId;
    }

    @JsonProperty("ConnectionSentId")
    public void setConnectionSentId(String ConnectionSentId) {
        this.ConnectionSentId = ConnectionSentId;
    }

    // BF_Emloyee_company__c
    private String BF_Emloyee_company__c;

    @JsonProperty("BF_Emloyee_company__c")
    public String getBF_Emloyee_company__c() {
        return this.BF_Emloyee_company__c;
    }

    @JsonProperty("BF_Emloyee_company__c")
    public void setBF_Emloyee_company__c(String BF_Emloyee_company__c) {
        this.BF_Emloyee_company__c = BF_Emloyee_company__c;
    }

    // BF_Emloyee_SignedAgreement__c
    private Boolean BF_Emloyee_SignedAgreement__c;

    @JsonProperty("BF_Emloyee_SignedAgreement__c")
    public Boolean getBF_Emloyee_SignedAgreement__c() {
        return this.BF_Emloyee_SignedAgreement__c;
    }

    @JsonProperty("BF_Emloyee_SignedAgreement__c")
    public void setBF_Emloyee_SignedAgreement__c(Boolean BF_Emloyee_SignedAgreement__c) {
        this.BF_Emloyee_SignedAgreement__c = BF_Emloyee_SignedAgreement__c;
    }

    // BF_Emloyee_category__c
    @XStreamConverter(PicklistEnumConverter.class)
    private String BF_Emloyee_category__c;

    @JsonProperty("BF_Emloyee_category__c")
    public String getBF_Emloyee_category__c() {
        return this.BF_Emloyee_category__c;
    }

    @JsonProperty("BF_Emloyee_category__c")
    public void setBF_Emloyee_category__c(String BF_Emloyee_category__c) {
        this.BF_Emloyee_category__c = BF_Emloyee_category__c;
    }

    // BF_Emloyee_email__c
    private String BF_Emloyee_email__c;

    @JsonProperty("BF_Emloyee_email__c")
    public String getBF_Emloyee_email__c() {
        return this.BF_Emloyee_email__c;
    }

    @JsonProperty("BF_Emloyee_email__c")
    public void setBF_Emloyee_email__c(String BF_Emloyee_email__c) {
        this.BF_Emloyee_email__c = BF_Emloyee_email__c;
    }

    // BF_Emloyee_name__c
    private String BF_Emloyee_name__c;

    @JsonProperty("BF_Emloyee_name__c")
    public String getBF_Emloyee_name__c() {
        return this.BF_Emloyee_name__c;
    }

    @JsonProperty("BF_Emloyee_name__c")
    public void setBF_Emloyee_name__c(String BF_Emloyee_name__c) {
        this.BF_Emloyee_name__c = BF_Emloyee_name__c;
    }

    // BF_Emloyee_patronymic__c
    private String BF_Emloyee_patronymic__c;

    @JsonProperty("BF_Emloyee_patronymic__c")
    public String getBF_Emloyee_patronymic__c() {
        return this.BF_Emloyee_patronymic__c;
    }

    @JsonProperty("BF_Emloyee_patronymic__c")
    public void setBF_Emloyee_patronymic__c(String BF_Emloyee_patronymic__c) {
        this.BF_Emloyee_patronymic__c = BF_Emloyee_patronymic__c;
    }

    // BF_Emloyee_position__c
    @XStreamConverter(PicklistEnumConverter.class)
    private String BF_Emloyee_position__c;

    @JsonProperty("BF_Emloyee_position__c")
    public String getBF_Emloyee_position__c() {
        return this.BF_Emloyee_position__c;
    }

    @JsonProperty("BF_Emloyee_position__c")
    public void setBF_Emloyee_position__c(String BF_Emloyee_position__c) {
        this.BF_Emloyee_position__c = BF_Emloyee_position__c;
    }

    // BF_Emloyee_socialnetwork__c
    private String BF_Emloyee_socialnetwork__c;

    @JsonProperty("BF_Emloyee_socialnetwork__c")
    public String getBF_Emloyee_socialnetwork__c() {
        return this.BF_Emloyee_socialnetwork__c;
    }

    @JsonProperty("BF_Emloyee_socialnetwork__c")
    public void setBF_Emloyee_socialnetwork__c(String BF_Emloyee_socialnetwork__c) {
        this.BF_Emloyee_socialnetwork__c = BF_Emloyee_socialnetwork__c;
    }

    // BF_Emloyee_speciality__c
    @XStreamConverter(PicklistEnumConverter.class)
    private String BF_Emloyee_speciality__c;

    @JsonProperty("BF_Emloyee_speciality__c")
    public String getBF_Emloyee_speciality__c() {
        return this.BF_Emloyee_speciality__c;
    }

    @JsonProperty("BF_Emloyee_speciality__c")
    public void setBF_Emloyee_speciality__c(String BF_Emloyee_speciality__c) {
        this.BF_Emloyee_speciality__c = BF_Emloyee_speciality__c;
    }

    // BF_Emloyee_tel__c
    private String BF_Emloyee_tel__c;

    @JsonProperty("BF_Emloyee_tel__c")
    public String getBF_Emloyee_tel__c() {
        return this.BF_Emloyee_tel__c;
    }

    @JsonProperty("BF_Emloyee_tel__c")
    public void setBF_Emloyee_tel__c(String BF_Emloyee_tel__c) {
        this.BF_Emloyee_tel__c = BF_Emloyee_tel__c;
    }

    // BF_Emloyee_typeofemployee__c
    @XStreamConverter(PicklistEnumConverter.class)
    private String BF_Emloyee_typeofemployee__c;

    @JsonProperty("BF_Emloyee_typeofemployee__c")
    public String getBF_Emloyee_typeofemployee__c() {
        return this.BF_Emloyee_typeofemployee__c;
    }

    @JsonProperty("BF_Emloyee_typeofemployee__c")
    public void setBF_Emloyee_typeofemployee__c(String BF_Emloyee_typeofemployee__c) {
        this.BF_Emloyee_typeofemployee__c = BF_Emloyee_typeofemployee__c;
    }

    // BF_TelemarketComment__c
    private String BF_TelemarketComment__c;

    @JsonProperty("BF_TelemarketComment__c")
    public String getBF_TelemarketComment__c() {
        return this.BF_TelemarketComment__c;
    }

    @JsonProperty("BF_TelemarketComment__c")
    public void setBF_TelemarketComment__c(String BF_TelemarketComment__c) {
        this.BF_TelemarketComment__c = BF_TelemarketComment__c;
    }

}
