/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Apr 06 14:36:58 MSK 2017
 */
package ru.breffi.entityTypeConverterImpl.employee.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.google.gson.annotations.SerializedName;

/**
 * Salesforce Enumeration DTO for picklist BF_Emloyee_position__c
 */
public enum Employee__c_BF_Emloyee_positionEnum {

    
	@SerializedName("Администратор")АДМИНИСТРАТОР("Администратор"),
   // Врач
   @SerializedName("Врач")ВРАЧ("Врач"),
   // Гл. врач
   @SerializedName("Гл. врач")ГЛ__ВРАЧ("Гл. врач"),
   // Зав. аптекой
   @SerializedName("Зав. аптекой")ЗАВ__АПТЕКОЙ("Зав. аптекой"),
   // Зав. кафедрой
   @SerializedName("Зав. кафедрой")ЗАВ__КАФЕДРОЙ("Зав. кафедрой"),
   // Зав. отделением
   @SerializedName("Зав. отделением")ЗАВ__ОТДЕЛЕНИЕМ("Зав. отделением"),
   // Зам. Гл. врача
   @SerializedName("Зам. Гл. врача")ЗАМ__ГЛ__ВРАЧА("Зам. Гл. врача"),
   // Маркетолог
   @SerializedName("Маркетолог")МАРКЕТОЛОГ("Маркетолог"),
   // Начмед
   @SerializedName("Начмед")НАЧМЕД("Начмед"),
   // Провизор
   @SerializedName("Провизор")ПРОВИЗОР("Провизор");

    final String value;

    private Employee__c_BF_Emloyee_positionEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Employee__c_BF_Emloyee_positionEnum fromValue(String value) {
        for (Employee__c_BF_Emloyee_positionEnum e : Employee__c_BF_Emloyee_positionEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
