/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Apr 06 14:36:58 MSK 2017
 */
package ru.breffi.entityTypeConverterImpl.employee.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.google.gson.annotations.SerializedName;

/**
 * Salesforce Enumeration DTO for picklist BF_Emloyee_typeofemployee__c
 */
public enum Employee__c_BF_Emloyee_typeofemployeeEnum {

    // Администратор
	@SerializedName("Администратор")АДМИНИСТРАТОР("Администратор"),
    // Врач
	@SerializedName("Врач")ВРАЧ("Врач"),
    // Ключевой клиент
	@SerializedName("Ключевой клиент")КЛЮЧЕВОЙ_КЛИЕНТ("Ключевой клиент"),
    // Провизор
	@SerializedName("Провизор")ПРОВИЗОР("Провизор");

    final String value;

    private Employee__c_BF_Emloyee_typeofemployeeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Employee__c_BF_Emloyee_typeofemployeeEnum fromValue(String value) {
        for (Employee__c_BF_Emloyee_typeofemployeeEnum e : Employee__c_BF_Emloyee_typeofemployeeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
