/*
 * Salesforce Query DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Apr 06 14:36:58 MSK 2017
 */
package ru.breffi.entityTypeConverterImpl.employee.dto;

import com.thoughtworks.xstream.annotations.XStreamImplicit;
import org.apache.camel.component.salesforce.api.dto.AbstractQueryRecordsBase;

import java.util.List;

/**
 * Salesforce QueryRecords DTO for type Employee__History
 */
public class QueryRecordsEmployee__History extends AbstractQueryRecordsBase {

    @XStreamImplicit
    private List<Employee__History> records;

    public List<Employee__History> getRecords() {
        return records;
    }

    public void setRecords(List<Employee__History> records) {
        this.records = records;
    }
}
