/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Apr 06 14:36:58 MSK 2017
 */
package ru.breffi.entityTypeConverterImpl.companyConverter.sfdto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist BF_Company_Facilitytype__c
 */
public enum BF_Company__c_BF_Company_FacilitytypeEnum {
   
	Женская_консультация("Женская консультация"),
   
	Поликлиника_взрослая("Поликлиника взрослая"),
   
	Поликлиника_детская("Поликлиника детская"),
   
	Стационар("Стационар"),
   
	Медицинский_центр("Медицинский центр"),
   
	Сетевая_аптека("Сетевая (аптека)"),
   
	Не_сетевая_аптека ("Не сетевая (аптека)"),
   
	WomenBlockф("Женское специализированное отделение");

    final String value;

    private BF_Company__c_BF_Company_FacilitytypeEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static BF_Company__c_BF_Company_FacilitytypeEnum fromValue(String value) {
        for (BF_Company__c_BF_Company_FacilitytypeEnum e : BF_Company__c_BF_Company_FacilitytypeEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
