/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Apr 06 14:36:58 MSK 2017
 */
package ru.breffi.entityTypeConverterImpl.companyConverter.sfdto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist BF_Company_ManagmentView__c
 */
public enum BF_Company__c_BF_Company_ManagmentViewEnum {

    // Ведомственная
    ВЕДОМСТВЕННАЯ("Ведомственная"),
    // Коммерческая
    КОММЕРЧЕСКАЯ("Коммерческая"),
    // Муниципальная
    МУНИЦИПАЛЬНАЯ("Муниципальная");

    final String value;

    private BF_Company__c_BF_Company_ManagmentViewEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static BF_Company__c_BF_Company_ManagmentViewEnum fromValue(String value) {
        for (BF_Company__c_BF_Company_ManagmentViewEnum e : BF_Company__c_BF_Company_ManagmentViewEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
