/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Apr 06 14:36:58 MSK 2017
 */
package ru.breffi.entityTypeConverterImpl.companyConverter.sfdto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;
import org.apache.camel.component.salesforce.api.PicklistEnumConverter;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Salesforce DTO for SObject BF_Company__c
 */
@XStreamAlias("BF_Company__c")
public class BF_Company__c extends AbstractSObjectBase {

    // ConnectionReceivedId
    private String ConnectionReceivedId;

    @JsonProperty("ConnectionReceivedId")
    public String getConnectionReceivedId() {
        return this.ConnectionReceivedId;
    }

    @JsonProperty("ConnectionReceivedId")
    public void setConnectionReceivedId(String ConnectionReceivedId) {
        this.ConnectionReceivedId = ConnectionReceivedId;
    }

    // ConnectionSentId
    private String ConnectionSentId;

    @JsonProperty("ConnectionSentId")
    public String getConnectionSentId() {
        return this.ConnectionSentId;
    }

    @JsonProperty("ConnectionSentId")
    public void setConnectionSentId(String ConnectionSentId) {
        this.ConnectionSentId = ConnectionSentId;
    }

    // BF_City__c
    private String BF_City__c;

    @JsonProperty("BF_City__c")
    public String getBF_City__c() {
        return this.BF_City__c;
    }

    @JsonProperty("BF_City__c")
    public void setBF_City__c(String BF_City__c) {
        this.BF_City__c = BF_City__c;
    }

    // BF_Company_Facilitytype__c
    @XStreamConverter(PicklistEnumConverter.class)
    private String BF_Company_Facilitytype__c;

    @JsonProperty("BF_Company_Facilitytype__c")
    public String getBF_Company_Facilitytype__c() {
        return this.BF_Company_Facilitytype__c;
    }

    @JsonProperty("BF_Company_Facilitytype__c")
    public void setBF_Company_Facilitytype__c(String BF_Company_Facilitytype__c) {
        this.BF_Company_Facilitytype__c = BF_Company_Facilitytype__c;
    }

    // BF_Company_HQ__c
    private String BF_Company_HQ__c;

    @JsonProperty("BF_Company_HQ__c")
    public String getBF_Company_HQ__c() {
        return this.BF_Company_HQ__c;
    }

    @JsonProperty("BF_Company_HQ__c")
    public void setBF_Company_HQ__c(String BF_Company_HQ__c) {
        this.BF_Company_HQ__c = BF_Company_HQ__c;
    }

    // BF_Company_HQ_subsidiary__c
    private String BF_Company_HQ_subsidiary__c;

    @JsonProperty("BF_Company_HQ_subsidiary__c")
    public String getBF_Company_HQ_subsidiary__c() {
        return this.BF_Company_HQ_subsidiary__c;
    }

    @JsonProperty("BF_Company_HQ_subsidiary__c")
    public void setBF_Company_HQ_subsidiary__c(String BF_Company_HQ_subsidiary__c) {
        this.BF_Company_HQ_subsidiary__c = BF_Company_HQ_subsidiary__c;
    }

    // BF_Emloyee_County__c
    @XStreamConverter(PicklistEnumConverter.class)
    private String BF_Emloyee_County__c;

    @JsonProperty("BF_Emloyee_County__c")
    public String getBF_Emloyee_County__c() {
        return this.BF_Emloyee_County__c;
    }

    @JsonProperty("BF_Emloyee_County__c")
    public void setBF_Emloyee_County__c(String BF_Emloyee_County__c) {
        this.BF_Emloyee_County__c = BF_Emloyee_County__c;
    }

    // BF_Emloyee_Street__c
    private String BF_Emloyee_Street__c;
    
    @JsonProperty("BF_Emloyee_Street__c")
    public String getBF_Emloyee_Street__c() {
        return this.BF_Emloyee_Street__c;
    }

    @JsonProperty("BF_Emloyee_Street__c")
    public void setBF_Emloyee_Street__c(String BF_Emloyee_Street__c) {
        this.BF_Emloyee_Street__c = BF_Emloyee_Street__c;
    }

    // BF_Company_ManagmentView__c
    @XStreamConverter(PicklistEnumConverter.class)
    private String BF_Company_ManagmentView__c;

    @JsonProperty("BF_Company_ManagmentView__c")
    public String getBF_Company_ManagmentView__c() {
        return this.BF_Company_ManagmentView__c;
    }

    @JsonProperty("BF_Company_ManagmentView__c")
    public void setBF_Company_ManagmentView__c(String BF_Company_ManagmentView__c) {
        this.BF_Company_ManagmentView__c = BF_Company_ManagmentView__c;
    }

    // BF_Company_type__c
    @XStreamConverter(PicklistEnumConverter.class)
    private String BF_Company_type__c;

    @JsonProperty("BF_Company_type__c")
    public String getBF_Company_type__c() {
        return this.BF_Company_type__c;
    }

    @JsonProperty("BF_Company_type__c")
    public void setBF_Company_type__c(String BF_Company_type__c) {
        this.BF_Company_type__c = BF_Company_type__c;
    }

    // BF_Company_tel1__c
    private String BF_Company_tel1__c;

    @JsonProperty("BF_Company_tel1__c")
    public String getBF_Company_tel1__c() {
        return this.BF_Company_tel1__c;
    }

    @JsonProperty("BF_Company_tel1__c")
    public void setBF_Company_tel1__c(String BF_Company_tel1__c) {
        this.BF_Company_tel1__c = BF_Company_tel1__c;
    }

    // BF_Company_tel2__c
    private String BF_Company_tel2__c;

    @JsonProperty("BF_Company_tel2__c")
    public String getBF_Company_tel2__c() {
        return this.BF_Company_tel2__c;
    }

    @JsonProperty("BF_Company_tel2__c")
    public void setBF_Company_tel2__c(String BF_Company_tel2__c) {
        this.BF_Company_tel2__c = BF_Company_tel2__c;
    }

}
