/*
 * Salesforce Query DTO generated by camel-salesforce-maven-plugin
 * Generated on: Mon Mar 20 15:58:02 MSK 2017
 */
package ru.breffi.entityTypeConverterImpl.companyConverter.sfdto;

import com.thoughtworks.xstream.annotations.XStreamImplicit;
import org.apache.camel.component.salesforce.api.dto.AbstractQueryRecordsBase;

import java.util.List;

/**
 * Salesforce QueryRecords DTO for type BF_Company__c
 */
public class QueryRecordsBF_Company__c extends AbstractQueryRecordsBase {

    @XStreamImplicit
    private List<BF_Company__c> records;

    public List<BF_Company__c> getRecords() {
        return records;
    }

    public void setRecords(List<BF_Company__c> records) {
        this.records = records;
    }
}
